# SEO
title: Android Porting Toolkit
description: Guide for porting custom ROMs, GSIs, Recoveries, and fixes for Android devices.
url: "https://rajdeep-3305.github.io/android-porting-guide"
author: Rajdeep

title: Android Porting Toolkit
description: Full guide to ROM/GSI/Recovery porting with tools and fixes
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
